[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Qingrong Ke <keqingrong1992@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
